# Generated by Django 5.0.14 on 2025-09-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cuentas', '0002_departamento_localidad_provincia_remove_alumno_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='online',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='presencial',
        ),
        migrations.AddField(
            model_name='alumno',
            name='materias_interes',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='catalogo.materia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='modalidad',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Ambos', 'Ambos')], default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='disponibilidad',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='cuentas.disponibilidad'),
        ),
        migrations.AddField(
            model_name='maestro',
            name='idiomas',
            field=models.ManyToManyField(blank=True, related_name='maestros', to='cuentas.idioma'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.niveleducativo'),
        ),
    ]
