# Generated by Django 5.0.14 on 2025-09-24 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cuentas', '0004_usuario_apellido_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_clase_propuesta', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.alumno')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.materia')),
            ],
        ),
    ]
