# Generated by Django 5.0.14 on 2025-10-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_conversacion_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud', 'Nueva Solicitud'), ('mensaje', 'Mensaje Nuevo'), ('clase_aceptada', 'Clase Aceptada'), ('clase_rechazada', 'Clase Rechazada'), ('review', 'Nueva Reseña')], max_length=20)),
                ('mensaje', models.TextField()),
                ('enlace', models.CharField(blank=True, max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_escritas', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='cuentas.solicitudclase')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clase', 'autor')},
            },
        ),
    ]
