# Generated by Django 5.0.14 on 2025-10-02 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_notificacion_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='cbu_cvu_alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBU/CVU o Alias'),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='codigo_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='fecha_clase_confirmada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='monto_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='pago_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudclase',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudclase',
            name='fecha_clase_propuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DisponibilidadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('clase', 'Clase'), ('ocupacion', 'Ocupación Personal'), ('disponible', 'Disponible')], default='ocupacion', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
