# Generated by Django 5.0.14 on 2025-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_maestro_cbu_cvu_alias_solicitudclase_codigo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudclase',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('propuesta', 'Propuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
