# Generated by Django 5.2.7 on 2025-10-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_reseña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
