# Generated by Django 5.0.14 on 2025-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_delete_resena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudclase',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.RemoveField(
            model_name='solicitudclase',
            name='pago_realizado',
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
