# Generated by Django 5.0.14 on 2025-11-05 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_delete_resena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudclase',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.RemoveField(
            model_name='solicitudclase',
            name='pago_realizado',
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlocNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReseñaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to='cuentas.alumno')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.maestro')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseña_alumno', to='cuentas.solicitudclase')),
            ],
            options={
                'verbose_name': 'Reseña de Alumno',
                'verbose_name_plural': 'Reseñas de Alumnos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('estudio_libre', 'Estudio Libre')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', '🔵 Baja'), ('media', '🟡 Media'), ('alta', '🔴 Alta')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_progreso', '🔄 En Progreso'), ('completada', '✅ Completada')], default='pendiente', max_length=15)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
