# Generated by Django 5.0.14 on 2025-10-29 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_alter_solicitudclase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseñaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to='cuentas.alumno')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.maestro')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseña_alumno', to='cuentas.solicitudclase')),
            ],
            options={
                'verbose_name': 'Reseña de Alumno',
                'verbose_name_plural': 'Reseñas de Alumnos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
