# Generated by Django 5.0.14 on 2025-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_institucion_promocion_remove_blocnotas_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='mensajes/archivos/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes/imagenes/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tamano_archivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('archivo', 'Archivo')], default='texto', max_length=10),
        ),
    ]
