# Generated by Django 5.0.14 on 2026-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_ticketsoporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('archivo', 'Archivo'), ('audio', 'Audio')], default='texto', max_length=10),
        ),
    ]
