# Generated by Django 5.0.14 on 2026-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_alter_mensaje_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudclase',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado_alumno', 'Pagado por alumno (pendiente verificación)'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
