# Generated by Django 5.0.14 on 2026-05-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0017_alter_solicitudclase_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadusuario',
            name='tipo',
            field=models.CharField(choices=[('clase', 'Clase'), ('ocupacion', 'Ocupación Personal'), ('disponible', 'Disponible'), ('evento', 'Evento')], default='ocupacion', max_length=20),
        ),
    ]
